### ISSUE TITLE
Is there a way to keep the HUD from stretching or add a proper 21:9 HUD?

### ISSUE THREAD

**Issue by CodingPigFromTheBushes** [PrismaticFlower/shaderpatch#136]
Your shaderpatch mod is a godsend to me as 21:9 gamer since before this patch there was no way to get a playable HUD into the game.

I tried a lot of solutions and came to the conclusion that a 16:10 HUD actually looks the best on my 21:9 screen as it stands, at least that was the best solution I was able to come up with since others do not work.

I was not able to make the HUD display properly in 16:9 or 21:9 since for some reason it is always stretched to fullscreen which is 2560x1080 on my end. I wouldn't even mind if the HUD would stay in 1920x1080 but not stretch to the corners of the screen but so far I wasn't able to do that. Of course best would be to have a working 21:9 HUD but whenever I try to make the HUD 21:9 its completely broken and unusable and it seems like no modder made a 21:9 HUD ever so far. I was also not able to make the HUD smaller since it is always displayed at the same size even with that scalling option in the shaderpatch config file which seems needlessly big and I wouldnt mind it half the size.

**Comment by SleepKiller** [comment]
hmm, not easily I'm afraid. The current way I can think of (which might not be the only way) is to track down and patch the game's assembly code for HUD layout directly. Thus far this avoids patching the game like that to give it the greatest chance at compatibility across the different builds of the game but this could be done as an optional feature I suppose.

I really like the idea of having better support for aspect ratios other than 4:3 and 16:9. I am quite busy working on other things at the moment though so I won't be able to offer any assurances of when I can look at this more sadly. Thanks for the feedback though it's good to know about this stuff.

**Comment by PrismaticFlower** [comment]
Fixed in [v1.7.1](https://github.com/PrismaticFlower/shaderpatch/releases/tag/v1.7.1).
