### ISSUE TITLE
How to enable 4K resolution?

### ISSUE THREAD

**Issue by jpcarstech** [PrismaticFlower/shaderpatch#142]
Hi, with the vanilla game, I am able to force to 4K. Obviously it has UI scaling issues. However, with shaderpatch installed, scaling is fixed, but I'm only able to go up to 2560 x 1440. Even if I try to force via command line or by editing the vidmode.ini. Hope someone knows how to get to 4K res. Thanks!

**Comment by PrismaticFlower** [comment]
Shader Patch unfortunately doesn't have support for legacy fullscreen exclusive mode and as a result can't change the display mode. When using it you're stuck at what your desktop resolution is. It's not ideal for cases like yours and I've often wanted to go back and add support for it but I've never managed to get to it.

**Comment by PrismaticFlower** [comment]
Fixed in [v1.7.1](https://github.com/PrismaticFlower/shaderpatch/releases/tag/v1.7.1).
