### ISSUE TITLE
HUD is upside down / inverted

### ISSUE THREAD

**Issue by Aerospacesmith** [PrismaticFlower/shaderpatch#143]
So I've got a strange issue that I can't figure out: all the HUD UI is being rendered upside down. 
The menu UI is correct, but the text on the loading screen is not formatted correctly.
The spawn menu is correct, but the spawn map is all distorted.

I'm running the latest 1.7.0 Shader Patch and have tried several options but none of them have fixed this issue, at least not without creating other aspect issues. I'm running a 32:9 display and everything is working and rendering correctly, except for the HUD.

![20240316115210_1](https://github.com/PrismaticFlower/shaderpatch/assets/5132118/ef53cf45-fab9-45ae-9983-9bc0d47e8ee7)
![20240316115221_1](https://github.com/PrismaticFlower/shaderpatch/assets/5132118/6ad09f53-6311-4bcf-af0b-f32bbc341251)
![20240316115232_1](https://github.com/PrismaticFlower/shaderpatch/assets/5132118/e169e56f-c249-4948-bb03-df28277528aa)
![20240316115528_1](https://github.com/PrismaticFlower/shaderpatch/assets/5132118/b15c8f72-14c0-433e-b39c-dee134625fbc)

**Comment by PrismaticFlower** [comment]
Fixed (kind of) in [v1.7.1](https://github.com/PrismaticFlower/shaderpatch/releases/tag/v1.7.1).
