### ISSUE TITLE
Droideka shield is blinding levels of bright.

### ISSUE THREAD

**Issue by TwinGalaxy** [PrismaticFlower/shaderpatch#144]
As the title says, the Droideka shield is blindingly bright on some maps. Kashyyyk being one of the worst offenders. I've tried fiddling with the settings, including turning off bloom both in game and in the patch config, but it seems to always be there, unless I turn the patch off entirely. Any way to fix it? It's still playable but makes huge parts of certain maps basically impossible to see in while having a Droideka shield up.
![6060_20240316182337_1](https://github.com/PrismaticFlower/shaderpatch/assets/114189761/c286f996-c0b5-4954-9616-29f15e17cf6e)

**Comment by PrismaticFlower** [comment]
Hi! I've tracked down what was causing this and fixed it. I'll be posting a new release later on containing it and will post another message here when that's done.
