### ISSUE TITLE
Game crashes with a black screen when trying to use this mod with BF2 on Proton/Linux.

### ISSUE THREAD

**Issue by KingKrouch** [PrismaticFlower/shaderpatch#146]
I've noticed that the game seemingly crashes on startup when I attempt to run this mod on Proton. I can confirm that I have installed the Visual C++ 2022 Redistributables, as the build instructions seem to suggest that it's compiled with VS 2022, but there still isn't much of a difference.

[shader patch.log](https://github.com/PrismaticFlower/shaderpatch/files/14644371/shader.patch.log)
Here is what my current config looks like: https://gist.github.com/KingKrouch/757fa7408fb5426a902fa6a3b5f355ff

**Comment by PrismaticFlower** [comment]
Check out the steps here. Sounds like it could be the same/similar thing. https://github.com/PrismaticFlower/shaderpatch/issues/132#issuecomment-2002061416 If I have time I will try to improve the situation for the next update.

**Comment by BENDER-V2** [comment]
yep he just needs to change the font in the shaderpatch.yml

**Comment by PrismaticFlower** [comment]
Should be fixed in [v1.7.1](https://github.com/PrismaticFlower/shaderpatch/releases/tag/v1.7.1).
