### ISSUE TITLE
V 1.7.1 Bloom Lighting issue

### ISSUE THREAD

**Issue by FluffyWerewolf** [PrismaticFlower/shaderpatch#148]
When using the latest version of the shader patch none of the bloom effects actually seem to work correctly the issue gets resolved when using V 1.7.0. 

![20240331161815_1](https://github.com/PrismaticFlower/shaderpatch/assets/123856759/d3c8e31d-ab0a-4ec1-ad56-9b7be6763514)

![20240331161811_1](https://github.com/PrismaticFlower/shaderpatch/assets/123856759/3718a222-7148-409c-bc0e-832af4ef07f9)

**Comment by PrismaticFlower** [comment]
That's no good. Can you attach your `shader patch.yml` and `shader patch.log` here? And (if you know it) what's your resolution and refresh rate?

**Comment by FluffyWerewolf** [comment]
I've gone ahead and have attached the shader patch.yml and the shader patch.log via my google drive.
https://drive.google.com/drive/folders/105qlUcL30xoIFuqfSeIAeqnF2Aro2tDh?usp=sharing

The resolution i'm running is 3840x2160 and the refresh rate is 120hz

**Comment by PrismaticFlower** [comment]
Thanks for the detailed info! I was able to track down the issue by using that same resolution. A fix is in the [latest release](https://github.com/PrismaticFlower/shaderpatch/releases/latest).

**Comment by FluffyWerewolf** [comment]
Thank You I went ahead and installed V 1.7.2 and can confirm that the issue with the lack of bloom has been fixed 
![20240401080626_1](https://github.com/PrismaticFlower/shaderpatch/assets/123856759/77dba7e3-b6cd-4045-b5b9-43820a3b622e)

**Comment by PrismaticFlower** [comment]
Glad to hear! Thank you for confirming it as well.
